//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoritmoGenetico.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlgoritmoGenetico.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N,O;N,S;N,S;N,S;N,L;N,O;N,S;N,S;N,L;N,O;L,O;N,S,O;N,S;N,S;S,L;L,O;N,O;N,L;O,S;S,L;O;N,S;N,S;N,S;N,S;L;L,O,S;O;N,S;N,L;O,S;N,S;N,S;N,L;O,N,S;S;N,S;S,L;N,O,L;L,O;N,O;N,S,L;N,O;L;N,O;N,S;N,S;N,S;S,L;O,S;O,S;N,S;L;O;S;N,S;N,S;N,S;N,S;N,L;N,O;N,S;S,L;L,O;N,S,O;N;N,L;O,N;N,S;S,L;O;N;N,S;S;N;L;L,O;O,S;N,S;N,L;L,O;L,O;O,N,S;N,S,L;L,O;L,O;O,S;N,S;N,S;L;S,L;O,S;N,S;N,S;S,L;O,S;N,S;N,S;N,S;S,L.
        /// </summary>
        public static string MazeStructure {
            get {
                return ResourceManager.GetString("MazeStructure", resourceCulture);
            }
        }
    }
}
